export const LOGIN_RESOLVE = 'LOGIN_RESOLVE';
export const LOGOUT_RESOLVE = 'LOGOUT_RESOLVE';
export const GET_PASSWORDS = 'GET_PASSWORDS';
export const REMOVE_PASSWORD = 'REMOVE_PASSWORD';
export const ADD_PASSWORD = 'ADD_PASSWORD';
export const EDIT_PASSWORD = 'EDIT_PASSWORD';
export const RESET_PASSWORDS = 'RESET_PASSWORDS';